// apps/react/src/pages/Checkout.tsx
import { IonButton, IonContent, IonFooter, IonHeader, IonIcon, IonItem, IonLabel, IonList, IonListHeader, IonPage, IonSlide, IonSlides, IonTitle, IonToolbar, useIonRouter, useIonViewDidEnter } from '@ionic/react';
import { chevronBack } from 'ionicons/icons';

import { useRef, useState } from 'react';

import { FormattedNumber } from 'react-intl';

import './Checkout.scss';

import BillingForm from '../components/BillingForm';
import ShippingForm from '../components/ShippingForm';
import CardForm from '../components/CardForm';

const MultiStepForm: React.FC = () => {

  const ionSlides = useRef<HTMLIonSlidesElement>(null);
  const ionContent = useRef<HTMLIonContentElement>(null);
  const billingFormRef = useRef<any>(null);
  const shippingFormRef = useRef<any>(null);
  const cardFormRef = useRef<any>(null);

  const ionRouter = useIonRouter();

  const [cart] = useState({
    id: 1,
    items: [{
      id: 1,
      name: 'Denim T-Shirt',
      amount: 15.00,
    }, {
      id: 2,
      name: 'Denim Pants',
      amount: 5.00,
    }, {
      id: 3,
      name: 'Black T-Shirt',
      amount: 5.00,
    }],
    subtotal: 25.00,
    shippingFee: 5.00,
    total: 30.00,
  });

  const [slides] = useState<string[]>(['Billing', 'Shipping', 'Summary', 'Payment']);
  const [currentSlide, setIsCurrentSlide] = useState('Billing');
  const [isBeginning, setIsBeginning] = useState(true);
  const [isEnd, setIsEnd] = useState(false);

  const [formData, setFormData] = useState<any>({});

  useIonViewDidEnter(() => {
    ionSlides.current!.update();
    ionSlides.current!.updateAutoHeight();
  }, []);

  const slidesOpts = {
    allowTouchMove: false,
    autoHeight: true,
  };

  const camel2title = (camelCase: string) => {
    return camelCase
      .replace(/([A-Z])/g, (match) => ` ${match}`)
      .replace(/^./, (match) => match.toUpperCase())
      .trim();
  }

  const onSlidesWillChange = async () => {
    const index = await ionSlides.current!.getActiveIndex();
    const isBeginning = await ionSlides.current!.isBeginning();
    const isEnd = await ionSlides.current!.isEnd();

    setIsCurrentSlide(slides[index]);
    setIsBeginning(isBeginning);
    setIsEnd(isEnd);
  }

  const onSlidesDidChange = () => {
    ionContent.current!.scrollToTop();
  }

  const onBackButtonTouched = () => {
    ionSlides.current!.slidePrev();
    ionContent.current!.scrollToTop();
  }

  const onNextButtonTouched = async () => {

    if (currentSlide === 'Billing') {

      const isValid = await billingFormRef.current!.onTrigger();

      if (isValid) {

        setFormData({
          billing: billingFormRef.current!.getFormValues()
        });

        ionSlides.current!.slideNext();
        ionContent.current!.scrollToTop();
      }

    } else if (currentSlide === 'Shipping') {

      const isValid = await shippingFormRef.current!.onTrigger();

      if (isValid) {

        setFormData({
          shipping: shippingFormRef.current!.getFormValues(),
          ...formData,
        });

        ionSlides.current!.slideNext();
        ionContent.current!.scrollToTop();
      }

    } else if (currentSlide === 'Summary') {

      ionSlides.current!.slideNext();
      ionContent.current!.scrollToTop();

    } else if (currentSlide === 'Payment') {

      const isValid = await cardFormRef.current!.onTrigger();

      if (isValid) {

        setFormData({
          card: cardFormRef.current!.getFormValues(),
          ...formData,
        });

        ionRouter.push('/thanks', 'forward', 'replace');
      }
    }
  }

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar color="dark">
          <IonTitle>Checkout</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent ref={ionContent} className="ion-padding">
        <div>

          <div className="flex justify-content-space-between ion-margin-top relative">
            <div className="absolute full-width line"></div>

            {slides.map((slide: string, index: number) => {
              return (
                <div key={index} className="flex flex-column justify-content-center full-width">
                  <span className={`flex flex-column align-items-center justify-content-center align-self-center bold text-medium radius`}
                    style={{
                      background: slide === currentSlide ? 'var(--ion-color-success)' : 'var(--ion-color-light-shade)',
                      color: slide === currentSlide ? 'var(--ion-color-light)' : 'var(--ion-color-dark)',
                      width: '30px',
                      height: '30px'
                    }}
                  >
                    {index + 1}
                  </span>
                  <span style={{ color: slide === currentSlide ? 'var(--ion-color-success)' : 'var(--ion-color-dark)'}}
                    className={`flex text-medium bold ion-margin-vertical align-self-center`}>
                    {slide}
                  </span>
                </div>
              )
            })}
          </div>

          <IonSlides ref={ionSlides} options={slidesOpts} onIonSlideDidChange={onSlidesDidChange}
            onIonSlideWillChange={onSlidesWillChange}>
            {slides.map((slide: string, index: number) => {

              return (
                <IonSlide key={index}>
                  <div className="full-width ion-text-start">

                    {slide === 'Billing' && <BillingForm ref={billingFormRef} />}

                    {slide === 'Shipping' && <ShippingForm ref={shippingFormRef} />}

                    {slide === 'Summary' &&
                      <>
                        <IonListHeader className="ion-no-padding" style={{ minHeight: 'auto' }}>
                          <IonLabel className="ion-text-center bold ion-margin-bottom text-large" color="dark">Cart details</IonLabel>
                        </IonListHeader>

                        <p className="text-medium bold ion-text-uppercase">Billing details</p>
                        <div className="divider"></div>

                        <div>
                          {formData.billing && Object.entries(formData.billing).map(([key, value]) => {
                            return (
                              <p key={key} className="text-medium margin-v-sm">
                                <span className="bold">{camel2title(key)}:</span> {value}
                              </p>
                            )
                          })}
                        </div>

                        <div className="divider"></div>
                        <p className="text-medium bold ion-text-uppercase">Shipping details</p>
                        <div className="divider"></div>

                        <div>
                          {formData.shipping && Object.entries(formData.shipping).map(([key, value]) => {
                            return (
                              <p key={key} className="text-medium margin-v-sm">
                                <span className="bold">{camel2title(key)}:</span> {value}
                              </p>
                            )
                          })}
                        </div>

                        <div className="divider"></div>
                        <p className="text-medium bold ion-text-uppercase">Items</p>
                        <div className="divider"></div>

                        <IonList>
                          {cart.items.map((item: any) => {
                            return (
                              <IonItem key={item.id}>
                                <IonLabel>
                                  <h2 className="text-medium bold">{item.name}</h2>
                                </IonLabel>
                                <div>
                                  <span className="text-medium">
                                    <FormattedNumber value={item.amount} style="currency" currency="USD" />
                                  </span>
                                </div>
                              </IonItem>
                            )
                          })}

                          <IonItem>
                            <IonLabel>
                              <h2 className="text-medium bold">Subtotal</h2>
                            </IonLabel>
                            <div>
                              <span className="text-medium">
                                <FormattedNumber value={cart.subtotal} style="currency" currency="USD" />
                              </span>
                            </div>
                          </IonItem>
                          <IonItem>
                            <IonLabel>
                              <h2 className="text-medium bold">Shipping &amp; Handling</h2>
                            </IonLabel>
                            <div>
                              <span className="text-medium">
                                <FormattedNumber value={cart.shippingFee} style="currency" currency="USD" />
                              </span>
                            </div>
                          </IonItem>
                          <IonItem>
                            <IonLabel>
                              <h2 className="text-medium bold">Total</h2>
                            </IonLabel>
                            <div>
                              <span className="text-medium bold">
                                <FormattedNumber value={cart.total} style="currency" currency="USD" />
                              </span>
                            </div>
                          </IonItem>

                        </IonList>
                      </>
                    }

                    {slide === 'Payment' &&
                      <>
                        <CardForm ref={cardFormRef} />
                        <div className="ion-text-center">
                          <IonButton type="button" style={{ width: '200px' }} className="ion-margin-vertical" strong size="large"
                            shape="round" color="success" onClick={onNextButtonTouched}>Pay <FormattedNumber value={cart.total} style="currency" currency="USD" /></IonButton>
                        </div>

                        <div className="ion-text-center">
                          <IonButton type="button" style={{ width: '200px' }} className="ion-margin-vertical" strong size="large"
                            shape="round" color="medium" onClick={onBackButtonTouched}>Back</IonButton>
                        </div>
                      </>
                    }

                  </div>
                </IonSlide>

              )
            })}

          </IonSlides>

        </div>

      </IonContent >

      <IonFooter>
        <IonToolbar>
          <div className="full-width flex align-items-center ion-padding-horizontal justify-content-space-between">
            <IonButton style={{ width: '120px', visibility: isBeginning || isEnd ? 'hidden' : '' }} strong shape="round" color="dark" onClick={onBackButtonTouched}>
              <span>Back</span>
              <IonIcon slot="start" icon={chevronBack}></IonIcon>
            </IonButton>
            <IonButton style={{ width: '120px', visibility: isEnd ? 'hidden' : '' }} strong shape="round" color="success" onClick={onNextButtonTouched}>
              <span>Next</span>
            </IonButton>
          </div>
        </IonToolbar>
      </IonFooter>

    </IonPage >
  )
}

export default MultiStepForm;

// apps/vue/src/views/Checkout.vue
<template>
  <ion-page>
    <ion-header class="ion-no-border">
      <ion-toolbar color="dark">
        <ion-title>Checkout</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content class="ion-padding" ref="ionContent">
      <div>
        <div class="flex justify-content-space-between ion-margin-top relative">
          <div class="absolute full-width line"></div>
          <div
            class="flex flex-column justify-content-center full-width"
            v-for="(slide, index) in slides"
            :key="slide"
          >
            <span
              class="
                flex flex-column
                align-items-center
                justify-content-center
                align-self-center
                bold
                text-medium
                radius
              "
              :style="{
                background:
                  slide === currentSlide
                    ? 'var(--ion-color-success)'
                    : 'var(--ion-color-light-shade)',
                color:
                  slide === currentSlide
                    ? 'var(--ion-color-light)'
                    : 'var(--ion-color-dark)',
                width: '30px',
                height: '30px',
              }"
            >
              {{ index + 1 }}
            </span>
            <span
              :style="{
                color:
                  slide === currentSlide
                    ? 'var(--ion-color-success)'
                    : 'var(--ion-color-dark)',
              }"
              class="
                flex
                text-medium
                bold
                ion-margin-vertical
                align-self-center
              "
            >
              {{ slide }}
            </span>
          </div>
        </div>

        <ion-slides
          ref="ionSlides"
          :options="slidesOpts"
          @ionSlideDidChange="onSlidesDidChange()"
          @ionSlideWillChange="onSlidesChanged()"
        >
          <ion-slide v-for="slide in slides" :key="slide">
            <div class="full-width ion-text-start">
              <BillingForm ref="billingForm" v-if="slide === 'Billing'" />
              <ShippingForm ref="shippingForm" v-if="slide === 'Shipping'" />
              <div v-if="slide === 'Summary'">
                <ion-list-header
                  class="ion-no-padding"
                  style="min-height: auto"
                >
                  <ion-label class="ion-text-center ion-margin-bottom bold text-large" color="dark">
                    Order details
                  </ion-label>
                </ion-list-header>

                <div>
                  <p class="text-medium bold ion-text-uppercase">
                    Shipping details
                  </p>
                  <div class="divider"></div>

                  <div
                    v-for="(value, key, index) in formValues.shipping"
                    :key="index"
                  >
                    <p
                      class="text-medium margin-v-sm"
                      v-if="key !== 'attachment'"
                    >
                      <span class="bold"> {{ camel2title(key) }}: </span>
                      {{ value }}
                    </p>
                    <p
                      class="text-medium margin-v-sm"
                      v-if="key === 'attachment'"
                    >
                      <span class="bold"> Attachment: </span>
                      <img class="img-thumb" :src="value" />
                    </p>
                  </div>
                </div>

                <div>
                  <div class="divider"></div>
                  <p class="text-medium bold ion-text-uppercase">
                    Billing details
                  </p>
                  <div class="divider"></div>
                  <p
                    class="text-medium margin-v-sm"
                    v-for="(value, key, index) in formValues.billing"
                    :key="index"
                  >
                    <span class="bold"> {{ camel2title(key) }}: </span>
                    {{ value }}
                  </p>
                </div>

                <div class="divider"></div>
                <p class="text-medium bold ion-text-uppercase">Items</p>
                <div class="divider"></div>

                <ion-list>
                  <ion-item v-for="item in cart.items" :key="item.id">
                    <ion-label>
                      <h2 class="text-medium bold">{{ item.name }}</h2>
                    </ion-label>
                    <div>
                      <span class="text-medium">{{
                        $formatNumber(item.amount, {
                          style: "currency",
                          currency: "USD",
                          maximumFractionDigits: 8,
                        })
                      }}</span>
                    </div>
                  </ion-item>
                  <ion-item>
                    <ion-label>
                      <h2 class="text-medium bold">Subtotal</h2>
                    </ion-label>
                    <div>
                      <span class="text-medium">{{
                        $formatNumber(cart.subtotal, {
                          style: "currency",
                          currency: "USD",
                          maximumFractionDigits: 8,
                        })
                      }}</span>
                    </div>
                  </ion-item>
                  <ion-item>
                    <ion-label>
                      <h2 class="text-medium bold">Shipping &amp; Handling</h2>
                    </ion-label>
                    <div>
                      <span class="text-medium">{{
                        $formatNumber(cart.shippingFee, {
                          style: "currency",
                          currency: "USD",
                          maximumFractionDigits: 8,
                        })
                      }}</span>
                    </div>
                  </ion-item>
                  <ion-item>
                    <ion-label>
                      <h2 class="text-medium bold">Total</h2>
                    </ion-label>
                    <div>
                      <span class="text-medium bold">{{
                        $formatNumber(cart.total, {
                          style: "currency",
                          currency: "USD",
                          maximumFractionDigits: 8,
                        })
                      }}</span>
                    </div>
                  </ion-item>
                </ion-list>
              </div>
              <div v-if="slide === 'Payment'">
                <CardForm ref="cardForm" />

                <div class="ion-text-center">
                  <ion-button
                    type="button"
                    style="width: 200px"
                    class="ion-margin-vertical"
                    strong
                    size="large"
                    shape="round"
                    color="success"
                    @click="onNextButtonTouched"
                  >
                    Pay
                    {{
                      $formatNumber(cart.total, {
                        style: "currency",
                        currency: "USD",
                        maximumFractionDigits: 8,
                      })
                    }}
                  </ion-button>
                </div>

                <div class="ion-text-center">
                  <ion-button
                    type="button"
                    style="width: 200px"
                    class="ion-margin-vertical"
                    strong
                    size="large"
                    shape="round"
                    color="medium"
                    @click="onBackButtonTouched"
                  >
                    Back
                  </ion-button>
                </div>
              </div>
            </div>
          </ion-slide>
        </ion-slides>
      </div>
    </ion-content>
    <ion-footer>
      <ion-toolbar>
        <div
          class="
            full-width
            flex
            align-items-center
            ion-padding-horizontal
            justify-content-space-between
          "
        >
          <ion-button
            style="width: 120px"
            strong
            shape="round"
            color="dark"
            :style="{ visibility: isBeginning || isEnd ? 'hidden' : '' }"
            @click="onBackButtonTouched"
          >
            <span>Back</span>
            <ion-icon slot="start" :icon="chevronBack"></ion-icon>
          </ion-button>
          <ion-button
            style="width: 120px"
            strong
            shape="round"
            color="success"
            :style="{ visibility: isEnd ? 'hidden' : '' }"
            @click="onNextButtonTouched"
          >
            <span>Next</span>
          </ion-button>
        </div>
      </ion-toolbar>
    </ion-footer>
  </ion-page>
</template>

<script lang="ts">
import { computed, defineComponent, ref } from "vue";
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonContent,
  IonTitle,
  IonIcon,
  IonButton,
  IonSlides,
  IonSlide,
  IonFooter,
  IonLabel,
  IonListHeader,
  IonItem,
  IonList,
  onIonViewDidEnter,
} from "@ionic/vue";
import { chevronBack } from "ionicons/icons";
import { useRouter } from "vue-router";
import BillingForm from "@/components/BillingForm.vue";
import ShippingForm from "@/components/ShippingForm.vue";
import CardForm from "@/components/CardForm.vue";

export default defineComponent({
  name: "Checkout",
  setup() {
    const cart: any = {
      id: 1,
      items: [
        {
          id: 1,
          name: "Denim T-Shirt",
          amount: 15.0,
        },
        {
          id: 1,
          name: "Denim Pants",
          amount: 5.0,
        },
        {
          id: 1,
          name: "Black T-Shirt",
          amount: 5.0,
        },
      ],
      subtotal: 25.0,
      shippingFee: 5.0,
      total: 30.0,
    };

    const slidesOpts = {
      allowTouchMove: false,
      autoHeight: true,
    };

    const ionContent = ref();
    const ionSlides = ref();

    const billingForm = ref<InstanceType<typeof BillingForm>>();
    const shippingForm = ref<InstanceType<typeof ShippingForm>>();
    const cardForm = ref<InstanceType<typeof CardForm>>();

    const router = useRouter();

    onIonViewDidEnter(() => {
      ionSlides.value.$el.update();
      ionSlides.value.$el.updateAutoHeight();
    });

    const slides = ref(["Billing", "Shipping", "Summary", "Payment"]);
    const currentSlide = ref("Billing");
    const isBeginning = ref(true);
    const isEnd = ref(false);
    const formValues = ref({});

    const onSlidesChanged = async () => {
      const index = await ionSlides.value.$el.getActiveIndex();
      currentSlide.value = slides.value[index];
      isBeginning.value = await ionSlides.value.$el.isBeginning();
      isEnd.value = await ionSlides.value.$el.isEnd();
    };

    const onSlidesDidChange = () => {
      ionContent.value.$el.scrollToTop();
    };

    const onBackButtonTouched = () => {
      ionSlides.value.$el.slidePrev();
      ionContent.value.$el.scrollToTop();
    };

    const onNextButtonTouched = async () => {
      if (currentSlide.value === "Billing") {
        const form = await billingForm.value?.validate();

        if (form?.valid) {
          formValues.value = {
            billing: billingForm.value?.formValues,
            ...formValues.value,
          };

          ionSlides.value.$el.slideNext();
          ionContent.value.$el.scrollToTop();
        }
      } else if (currentSlide.value === "Shipping") {
        const form = await shippingForm.value?.validate();

        if (form?.valid) {
          formValues.value = {
            shipping: shippingForm.value?.formValues,
            ...formValues.value,
          };

          ionSlides.value.$el.slideNext();
          ionContent.value.$el.scrollToTop();
        }
      } else if (currentSlide.value === "Payment") {
        const form = await cardForm.value?.validate();

        if (form?.valid) {
          router.push({
            path: "/thanks",
            replace: true,
          });
        }
      } else {
        ionSlides.value.$el.slideNext();
        ionContent.value.$el.scrollToTop();
      }
    };

    const last = computed(() => slides.value.length - 1);

    const camel2title = (camelCase: string) => {
      return camelCase
        .replace(/([A-Z])/g, (match) => ` ${match}`)
        .replace(/^./, (match) => match.toUpperCase())
        .trim();
    };

    return {
      cart,
      slides,
      slidesOpts,
      currentSlide,
      isBeginning,
      isEnd,
      ionContent,
      ionSlides,
      onSlidesChanged,
      onSlidesDidChange,
      onBackButtonTouched,
      onNextButtonTouched,
      chevronBack,
      billingForm,
      shippingForm,
      cardForm,
      formValues,
      camel2title,
      last,
    };
  },
  components: {
    IonPage,
    IonHeader,
    IonContent,
    IonTitle,
    IonToolbar,
    IonIcon,
    IonSlides,
    IonSlide,
    IonButton,
    IonFooter,
    IonLabel,
    IonListHeader,
    IonItem,
    IonList,
    BillingForm,
    ShippingForm,
    CardForm,
  },
});
</script>

<style lang="scss" scoped>

ion-item {
  --border-color: var(--ion-color-light-tint);
}
ion-slides {
  height: 100%;

  ion-slide {
    align-items: flex-start;
  }

  .swiper-slide {
    visibility: hidden;
  }

  .swiper-slide.swiper-slide-active {
    visibility: visible;
  }
}

ion-item {
  --padding-start: 0;
}

.line {
  height: 3px;
  background: var(--ion-color-light-shade);
  top: 14px;
  z-index: -1;
}
</style>
